[project]
name = "space-game"
version = "0.2.0"
description = "Praktikums-Projekt: Schritt für Schritt ein Space-Shooter mit pygame in 11 Aufgaben"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pygame-ce>=2.5.7",
    "pymunk>=7.3.0",
    "space-game-entities",
    "space-game-physics",
    "space-game-ui",
    "space-game-utils",
]

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
space-game-ui = { workspace = true }
space-game-physics = { workspace = true }
space-game-entities = { workspace = true }
space-game-utils = { workspace = true }
